package com.waypointbible.app

import java.util.Calendar

data class DailyVerse(val ref: String, val text: String)

private val verses = listOf(
    DailyVerse("Lamentations 3:22-23", "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness."),
    DailyVerse("Isaiah 43:19", "Behold, I am doing a new thing; now it springs forth, do you not perceive it? I will make a way in the wilderness and rivers in the desert."),
    DailyVerse("Jeremiah 29:11", "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope."),
    DailyVerse("Romans 8:28", "And we know that for those who love God all things work together for good, for those who are called according to his purpose."),
    DailyVerse("Philippians 4:13", "I can do all things through him who strengthens me."),
    DailyVerse("Psalm 23:1", "The Lord is my shepherd; I shall not want."),
    DailyVerse("John 3:16", "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life."),
    DailyVerse("Matthew 11:28", "Come to me, all who labor and are heavy laden, and I will give you rest."),
    DailyVerse("Isaiah 40:31", "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint."),
    DailyVerse("Psalm 46:10", "Be still, and know that I am God. I will be exalted among the nations, I will be exalted in the earth!"),
    DailyVerse("Proverbs 3:5-6", "Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths."),
    DailyVerse("Romans 8:38-39", "For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord."),
    DailyVerse("Psalm 121:1-2", "I lift up my eyes to the hills. From where does my help come? My help comes from the Lord, who made heaven and earth."),
    DailyVerse("2 Corinthians 5:17", "Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come."),
    DailyVerse("John 14:27", "Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid."),
    DailyVerse("Psalm 34:18", "The Lord is near to the brokenhearted and saves the crushed in spirit."),
    DailyVerse("Isaiah 41:10", "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand."),
    DailyVerse("Matthew 5:4", "Blessed are those who mourn, for they shall be comforted."),
    DailyVerse("Psalm 103:12", "As far as the east is from the west, so far does he remove our transgressions from us."),
    DailyVerse("Romans 5:8", "But God shows his love for us in that while we were still sinners, Christ died for us."),
    DailyVerse("John 10:10", "I came that they may have life and have it abundantly."),
    DailyVerse("Psalm 27:1", "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?"),
    DailyVerse("Ephesians 2:8-9", "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast."),
    DailyVerse("Philippians 4:6-7", "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus."),
    DailyVerse("Psalm 51:10", "Create in me a clean heart, O God, and renew a right spirit within me."),
    DailyVerse("Isaiah 55:7", "Let the wicked forsake his way, and the unrighteous man his thoughts; let him return to the Lord, that he may have compassion on him, and to our God, for he will abundantly pardon."),
    DailyVerse("Luke 15:20", "And he arose and came to his father. But while he was still a long way off, his father saw him and felt compassion, and ran and embraced him and kissed him."),
    DailyVerse("Psalm 139:14", "I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well."),
    DailyVerse("1 John 1:9", "If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness."),
    DailyVerse("Zephaniah 3:17", "The Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing."),
    DailyVerse("Matthew 6:33", "But seek first the kingdom of God and his righteousness, and all these things will be added to you."),
    DailyVerse("John 8:36", "So if the Son sets you free, you will be free indeed."),
    DailyVerse("Psalm 37:4", "Delight yourself in the Lord, and he will give you the desires of your heart."),
    DailyVerse("Romans 12:2", "Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect."),
    DailyVerse("Hebrews 11:1", "Now faith is the assurance of things hoped for, the conviction of things not seen."),
    DailyVerse("Psalm 23:4", "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me; your rod and your staff, they comfort me."),
    DailyVerse("1 Corinthians 13:4-5", "Love is patient and kind; love does not envy or boast; it is not arrogant or rude. It does not insist on its own way; it is not irritable or resentful."),
    DailyVerse("John 15:5", "I am the vine; you are the branches. Whoever abides in me and I in him, he it is that bears much fruit, for apart from me you can do nothing."),
    DailyVerse("Psalm 91:1-2", "He who dwells in the shelter of the Most High will abide in the shadow of the Almighty. I will say to the Lord, My refuge and my fortress, my God, in whom I trust."),
    DailyVerse("James 1:2-3", "Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness."),
    DailyVerse("Isaiah 26:3", "You keep him in perfect peace whose mind is stayed on you, because he trusts in you."),
    DailyVerse("Galatians 5:22-23", "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law."),
    DailyVerse("Psalm 16:8", "I have set the Lord always before me; because he is at my right hand, I shall not be shaken."),
    DailyVerse("Romans 15:13", "May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope."),
    DailyVerse("Matthew 7:7", "Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you."),
    DailyVerse("2 Timothy 1:7", "For God gave us a spirit not of fear but of power and love and self-control."),
    DailyVerse("Psalm 32:8", "I will instruct you and teach you in the way you should go; I will counsel you with my eye upon you."),
    DailyVerse("John 14:6", "Jesus said to him, I am the way, and the truth, and the life. No one comes to the Father except through me."),
    DailyVerse("1 Peter 5:7", "Casting all your anxieties on him, because he cares for you."),
    DailyVerse("Psalm 119:105", "Your word is a lamp to my feet and a light to my path."),
    DailyVerse("Colossians 3:15", "And let the peace of Christ rule in your hearts, to which indeed you were called in one body. And be thankful."),
    DailyVerse("Isaiah 54:10", "For the mountains may depart and the hills be removed, but my steadfast love shall not depart from you, and my covenant of peace shall not be removed, says the Lord, who has compassion on you."),
    DailyVerse("Hebrews 4:16", "Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need."),
    DailyVerse("Psalm 62:1-2", "For God alone my soul waits in silence; from him comes my salvation. He alone is my rock and my salvation, my fortress; I shall not be greatly shaken."),
    DailyVerse("John 16:33", "I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world."),
    DailyVerse("Romans 8:1", "There is therefore now no condemnation for those who are in Christ Jesus."),
    DailyVerse("Psalm 73:26", "My flesh and my heart may fail, but God is the strength of my heart and my portion forever."),
    DailyVerse("Micah 7:8", "Rejoice not over me, O my enemy; when I fall, I shall rise; when I sit in darkness, the Lord will be a light to me."),
    DailyVerse("Matthew 5:6", "Blessed are those who hunger and thirst for righteousness, for they shall be satisfied."),
    DailyVerse("Psalm 86:5", "For you, O Lord, are good and forgiving, abounding in steadfast love to all who call upon you."),
    DailyVerse("Isaiah 43:1", "But now thus says the Lord, he who created you, O Jacob, he who formed you, O Israel: Fear not, for I have redeemed you; I have called you by name, you are mine."),
    DailyVerse("John 15:13", "Greater love has no one than this, that someone lay down his life for his friends."),
    DailyVerse("2 Corinthians 12:9", "But he said to me, My grace is sufficient for you, for my power is made perfect in weakness. Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me."),
    DailyVerse("Psalm 145:18", "The Lord is near to all who call on him, to all who call on him in truth."),
    DailyVerse("Luke 6:31", "And as you wish that others would do to you, do so to them."),
    DailyVerse("Ephesians 3:20", "Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us."),
    DailyVerse("Psalm 42:11", "Why are you cast down, O my soul, and why are you in turmoil within me? Hope in God; for I shall again praise him, my salvation and my God."),
    DailyVerse("Matthew 6:34", "Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble."),
    DailyVerse("Romans 10:9", "Because, if you confess with your mouth that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved."),
    DailyVerse("Psalm 55:22", "Cast your burden on the Lord, and he will sustain you; he will never permit the righteous to be moved."),
    DailyVerse("James 4:8", "Draw near to God, and he will draw near to you."),
    DailyVerse("John 11:25", "Jesus said to her, I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live."),
    DailyVerse("Isaiah 30:15", "For thus said the Lord God, the Holy One of Israel, In returning and rest you shall be saved; in quietness and in trust shall be your strength."),
    DailyVerse("Psalm 147:3", "He heals the brokenhearted and binds up their wounds."),
    DailyVerse("Colossians 1:17", "And he is before all things, and in him all things hold together."),
    DailyVerse("Revelation 21:4", "He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away."),
    DailyVerse("Psalm 130:3-4", "If you, O Lord, should mark iniquities, O Lord, who could stand? But with you there is forgiveness, that you may be feared."),
    DailyVerse("Matthew 28:20", "And behold, I am with you always, to the end of the age."),
    DailyVerse("Hebrews 12:1", "Therefore, since we are surrounded by so great a cloud of witnesses, let us also lay aside every weight, and sin which clings so closely, and let us run with endurance the race that is set before us."),
    DailyVerse("Psalm 18:2", "The Lord is my rock and my fortress and my deliverer, my God, my rock, in whom I take refuge, my shield, and the horn of my salvation, my stronghold."),
    DailyVerse("1 John 4:18", "There is no fear in love, but perfect love casts out fear."),
    DailyVerse("Luke 15:7", "Just so, I tell you, there will be more joy in heaven over one sinner who repents than over ninety-nine righteous persons who need no repentance."),
    DailyVerse("Psalm 40:1-2", "I waited patiently for the Lord; he inclined to me and heard my cry. He drew me up from the pit of destruction, out of the miry bog, and set my feet upon a rock, making my steps secure."),
    DailyVerse("Romans 8:26", "Likewise the Spirit helps us in our weakness. For we do not know what to pray for as we ought, but the Spirit himself intercedes for us with groanings too deep for words."),
    DailyVerse("John 6:35", "Jesus said to them, I am the bread of life; whoever comes to me shall not hunger, and whoever believes in me shall never thirst."),
    DailyVerse("Psalm 116:1-2", "I love the Lord, because he has heard my voice and my pleas for mercy. Because he inclined his ear to me, therefore I will call on him as long as I live."),
    DailyVerse("Galatians 2:20", "I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me."),
    DailyVerse("Isaiah 46:4", "Even to your old age I am he, and to gray hairs I will carry you. I have made, and I will bear; I will carry and will save."),
    DailyVerse("Psalm 19:14", "Let the words of my mouth and the meditation of my heart be acceptable in your sight, O Lord, my rock and my redeemer."),
    DailyVerse("Matthew 5:8", "Blessed are the pure in heart, for they shall see God."),
    DailyVerse("Hebrews 13:8", "Jesus Christ is the same yesterday and today and forever."),
    DailyVerse("John 20:29", "Jesus said to him, Have you believed because you have seen me? Blessed are those who have not seen and yet have believed."),
    DailyVerse("Psalm 31:24", "Be strong, and let your heart take courage, all you who wait for the Lord!"),
    DailyVerse("Romans 6:23", "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord."),
    DailyVerse("1 Corinthians 15:55", "O death, where is your victory? O death, where is your sting?"),
    DailyVerse("Psalm 30:5", "For his anger is but for a moment, and his favor is for a lifetime. Weeping may tarry for the night, but joy comes with the morning."),
    DailyVerse("Colossians 3:1", "If then you have been raised with Christ, seek the things that are above, where Christ is, seated at the right hand of God."),
    DailyVerse("Psalm 118:24", "This is the day that the Lord has made; let us rejoice and be glad in it."),
    DailyVerse("John 1:14", "And the Word became flesh and dwelt among us, and we have seen his glory, glory as of the only Son from the Father, full of grace and truth."),
    DailyVerse("Isaiah 25:8", "He will swallow up death forever; and the Lord God will wipe away tears from all faces."),
    DailyVerse("Psalm 22:24", "For he has not despised or scorned the suffering of the afflicted one; he has not hidden his face from him but has listened to his cry for help."),
    DailyVerse("Matthew 28:6", "He is not here, for he has risen, as he said."),
    DailyVerse("Psalm 16:11", "You make known to me the path of life; in your presence there is fullness of joy; at your right hand are pleasures forevermore."),
    DailyVerse("1 Peter 1:3", "Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead."),
    DailyVerse("John 14:1", "Let not your hearts be troubled. Believe in God; believe also in me."),
    DailyVerse("Psalm 28:7", "The Lord is my strength and my shield; in him my heart trusts, and I am helped; my heart exults, and with my song I give thanks to him."),
    DailyVerse("Ephesians 4:32", "Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you."),
    DailyVerse("Isaiah 53:5", "But he was pierced for our transgressions; he was crushed for our iniquities; upon him was the chastisement that brought us peace, and with his wounds we are healed."),
    DailyVerse("Psalm 36:7", "How precious is your steadfast love, O God! The children of mankind take refuge in the shadow of your wings."),
    DailyVerse("John 3:17", "For God did not send his Son into the world to condemn the world, but in order that the world might be saved through him."),
    DailyVerse("Psalm 46:1", "God is our refuge and strength, a very present help in trouble."),
    DailyVerse("Hebrews 6:19", "We have this as a sure and steadfast anchor of the soul, a hope that enters into the inner place behind the curtain."),
    DailyVerse("Luke 19:10", "For the Son of Man came to seek and to save the lost."),
    DailyVerse("Psalm 145:8", "The Lord is gracious and merciful, slow to anger and abounding in steadfast love."),
    DailyVerse("John 5:24", "Truly, truly, I say to you, whoever hears my word and believes him who sent me has eternal life. He does not come into judgment, but has passed from death to life."),
    DailyVerse("Psalm 103:8", "The Lord is merciful and gracious, slow to anger and abounding in steadfast love."),
    DailyVerse("Matthew 6:26", "Look at the birds of the air: they neither sow nor reap nor gather into barns, and yet your heavenly Father feeds them. Are you not of more value than they?"),
    DailyVerse("Romans 8:31", "What then shall we say to these things? If God is for us, who can be against us?"),
    DailyVerse("Psalm 84:11", "For the Lord God is a sun and shield; the Lord bestows favor and honor. No good thing does he withhold from those who walk uprightly."),
    DailyVerse("John 15:9", "As the Father has loved me, so have I loved you. Abide in my love."),
    DailyVerse("1 Thessalonians 5:16-18", "Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you."),
    DailyVerse("Psalm 9:9-10", "The Lord is a stronghold for the oppressed, a stronghold in times of trouble. And those who know your name put their trust in you, for you, O Lord, have not forsaken those who seek you."),
    DailyVerse("Isaiah 40:28-29", "Have you not known? Have you not heard? The Lord is the everlasting God, the Creator of the ends of the earth. He does not faint or grow weary. He gives power to the faint, and to him who has no might he increases strength."),
    DailyVerse("Matthew 5:3", "Blessed are the poor in spirit, for theirs is the kingdom of heaven."),
    DailyVerse("John 13:34", "A new commandment I give to you, that you love one another: just as I have loved you, you also are to love one another."),
    DailyVerse("Psalm 71:5", "For you, O Lord, are my hope, my trust, O Lord, from my youth."),
    DailyVerse("Philippians 1:6", "And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ."),
    DailyVerse("1 John 3:1", "See what kind of love the Father has given to us, that we should be called children of God; and so we are."),
    DailyVerse("Psalm 56:3", "When I am afraid, I put my trust in you."),
    DailyVerse("Isaiah 61:1", "The Spirit of the Lord God is upon me, because the Lord has anointed me to bring good news to the poor; he has sent me to bind up the brokenhearted, to proclaim liberty to the captives."),
    DailyVerse("John 8:12", "Again Jesus spoke to them, saying, I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life."),
    DailyVerse("Psalm 107:1", "Oh give thanks to the Lord, for he is good, for his steadfast love endures forever!"),
    DailyVerse("Hebrews 10:23", "Let us hold fast the confession of our hope without wavering, for he who promised is faithful."),
    DailyVerse("Matthew 18:20", "For where two or three are gathered in my name, there am I among them."),
    DailyVerse("Psalm 63:1", "O God, you are my God; earnestly I seek you; my soul thirsts for you; my flesh faints for you, as in a dry and weary land where there is no water."),
    DailyVerse("Romans 8:15", "For you did not receive the spirit of slavery to fall back into fear, but you have received the Spirit of adoption as sons, by whom we cry, Abba! Father!"),
    DailyVerse("John 4:14", "But whoever drinks of the water that I will give him will never be thirsty again. The water that I will give him will become in him a spring of water welling up to eternal life."),
    DailyVerse("Psalm 100:4-5", "Enter his gates with thanksgiving, and his courts with praise! Give thanks to him; bless his name! For the Lord is good; his steadfast love endures forever, and his faithfulness to all generations."),
    DailyVerse("Ephesians 1:7", "In him we have redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace."),
    DailyVerse("Isaiah 43:25", "I, I am he who blots out your transgressions for my own sake, and I will not remember your sins."),
    DailyVerse("Luke 11:9", "And I tell you, ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you."),
    DailyVerse("1 Corinthians 10:13", "No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape."),
    DailyVerse("Psalm 4:8", "In peace I will both lie down and sleep; for you alone, O Lord, make me dwell in safety."),
    DailyVerse("Matthew 11:29", "Take my yoke upon you, and learn from me, for I am gentle and lowly in heart, and you will find rest for your souls."),
    DailyVerse("Romans 5:1", "Therefore, since we have been justified by faith, we have peace with God through our Lord Jesus Christ."),
    DailyVerse("Psalm 138:8", "The Lord will fulfill his purpose for me; your steadfast love, O Lord, endures forever. Do not forsake the work of your hands."),
    DailyVerse("John 14:16", "And I will ask the Father, and he will give you another Helper, to be with you forever."),
    DailyVerse("Isaiah 58:11", "And the Lord will guide you continually and satisfy your desire in scorched places and make your bones strong; and you shall be like a watered garden, like a spring of water, whose waters do not fail."),
    DailyVerse("Galatians 6:9", "And let us not grow weary of doing good, for in due season we will reap, if we do not give up."),
    DailyVerse("John 16:22", "So also you have sorrow now, but I will see you again, and your hearts will rejoice, and no one will take your joy from you."),
    DailyVerse("Psalm 126:5", "Those who sow in tears shall reap with shouts of joy!"),
    DailyVerse("Matthew 5:9", "Blessed are the peacemakers, for they shall be called sons of God."),
    DailyVerse("Psalm 50:15", "And call upon me in the day of trouble; I will deliver you, and you shall glorify me."),
    DailyVerse("1 John 4:7", "Beloved, let us love one another, for love is from God, and whoever loves has been born of God and knows God."),
    DailyVerse("Isaiah 48:17", "Thus says the Lord, your Redeemer, the Holy One of Israel: I am the Lord your God, who teaches you to profit, who leads you in the way you should go."),
    DailyVerse("Psalm 68:19", "Blessed be the Lord, who daily bears us up; God is our salvation."),
    DailyVerse("John 10:27-28", "My sheep hear my voice, and I know them, and they follow me. I give them eternal life, and they will never perish, and no one will snatch them out of my hand."),
    DailyVerse("Hebrews 4:12", "For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart."),
    DailyVerse("Romans 8:37", "No, in all these things we are more than conquerors through him who loved us."),
    DailyVerse("Psalm 131:2", "But I have calmed and quieted my soul, like a weaned child with its mother; like a weaned child is my soul within me."),
    DailyVerse("Ephesians 2:10", "For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them."),
    DailyVerse("John 6:37", "All that the Father gives me will come to me, and whoever comes to me I will never cast out."),
    DailyVerse("Psalm 86:15", "But you, O Lord, are a God merciful and gracious, slow to anger and abounding in steadfast love and faithfulness."),
    DailyVerse("Isaiah 40:1", "Comfort, comfort my people, says your God."),
    DailyVerse("Psalm 23:6", "Surely goodness and mercy shall follow me all the days of my life, and I shall dwell in the house of the Lord forever."),
    DailyVerse("2 Corinthians 4:17", "For this light momentary affliction is preparing for us an eternal weight of glory beyond all comparison."),
    DailyVerse("John 15:4", "Abide in me, and I in you. As the branch cannot bear fruit by itself, unless it abides in the vine, neither can you, unless you abide in me."),
    DailyVerse("Psalm 34:8", "Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!"),
    DailyVerse("Romans 8:18", "For I consider that the sufferings of this present time are not worth comparing with the glory that is to be revealed to us."),
    DailyVerse("Psalm 91:11", "For he will command his angels concerning you to guard you in all your ways."),
    DailyVerse("John 11:35", "Jesus wept."),
    DailyVerse("Isaiah 55:8-9", "For my thoughts are not your thoughts, neither are your ways my ways, declares the Lord. For as the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts."),
    DailyVerse("Psalm 37:23-24", "The steps of a man are established by the Lord, when he delights in his way; though he fall, he shall not be cast headlong, for the Lord upholds his hand."),
    DailyVerse("Colossians 3:23", "Whatever you do, work heartily, as for the Lord and not for men."),
    DailyVerse("Psalm 139:7-8", "Where shall I go from your Spirit? Or where shall I flee from your presence? If I ascend to heaven, you are there! If I make my bed in Sheol, you are there!"),
    DailyVerse("Matthew 5:14", "You are the light of the world. A city set on a hill cannot be hidden."),
    DailyVerse("Psalm 119:11", "I have stored up your word in my heart, that I might not sin against you."),
    DailyVerse("1 Corinthians 13:13", "So now faith, hope, and love abide, these three; but the greatest of these is love."),
    DailyVerse("Psalm 27:14", "Wait for the Lord; be strong, and let your heart take courage; wait for the Lord!"),
    DailyVerse("Isaiah 55:12", "For you shall go out in joy and be led forth in peace; the mountains and the hills before you shall break forth into singing, and all the trees of the field shall clap their hands."),
    DailyVerse("Philippians 3:14", "I press on toward the goal for the prize of the upward call of God in Christ Jesus."),
    DailyVerse("Psalm 34:4", "I sought the Lord, and he answered me and delivered me from all my fears."),
    DailyVerse("John 1:12", "But to all who did receive him, who believed in his name, he gave the right to become children of God."),
    DailyVerse("Matthew 7:12", "So whatever you wish that others would do to you, do also to them, for this is the Law and the Prophets."),
    DailyVerse("Psalm 19:1", "The heavens declare the glory of God, and the sky above proclaims his handiwork."),
    DailyVerse("Hebrews 12:2", "Looking to Jesus, the founder and perfecter of our faith, who for the joy that was set before him endured the cross, despising the shame, and is seated at the right hand of the throne of God."),
    DailyVerse("Isaiah 43:2", "When you pass through the waters, I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you."),
    DailyVerse("John 15:16", "You did not choose me, but I chose you and appointed you that you should go and bear fruit and that your fruit should abide."),
    DailyVerse("Psalm 73:28", "But for me it is good to be near God; I have made the Lord God my refuge, that I may tell of all your works."),
    DailyVerse("Matthew 19:26", "But Jesus looked at them and said, With man this is impossible, but with God all things are possible."),
    DailyVerse("1 Peter 2:9", "But you are a chosen race, a royal priesthood, a holy nation, a people for his own possession, that you may proclaim the excellencies of him who called you out of darkness into his marvelous light."),
    DailyVerse("John 8:32", "And you will know the truth, and the truth will set you free."),
    DailyVerse("Psalm 119:114", "You are my hiding place and my shield; I hope in your word."),
    DailyVerse("Isaiah 26:4", "Trust in the Lord forever, for the Lord God is an everlasting rock."),
    DailyVerse("John 6:47", "Truly, truly, I say to you, whoever believes has eternal life."),
    DailyVerse("Proverbs 4:23", "Keep your heart with all vigilance, for from it flow the springs of life."),
    DailyVerse("Matthew 7:24", "Everyone then who hears these words of mine and does them will be like a wise man who built his house on the rock."),
    DailyVerse("Psalm 91:4", "He will cover you with his pinions, and under his wings you will find refuge; his faithfulness is a shield and buckler."),
    DailyVerse("Ephesians 6:10", "Finally, be strong in the Lord and in the strength of his might."),
    DailyVerse("John 17:17", "Sanctify them in the truth; your word is truth."),
    DailyVerse("Psalm 29:11", "May the Lord give strength to his people! May the Lord bless his people with peace!"),
    DailyVerse("Isaiah 33:2", "O Lord, be gracious to us; we wait for you. Be our arm every morning, our salvation in the time of trouble."),
    DailyVerse("Psalm 90:14", "Satisfy us in the morning with your steadfast love, that we may rejoice and be glad all our days."),
    DailyVerse("1 John 5:14", "And this is the confidence that we have toward him, that if we ask anything according to his will he hears us."),
    DailyVerse("John 10:11", "I am the good shepherd. The good shepherd lays down his life for the sheep."),
    DailyVerse("Matthew 6:19-20", "Do not lay up for yourselves treasures on earth, where moth and rust destroy and where thieves break in and steal, but lay up for yourselves treasures in heaven."),
    DailyVerse("Psalm 143:8", "Let me hear in the morning of your steadfast love, for in you I trust. Make me know the way I should go, for to you I lift up my soul."),
    DailyVerse("Hebrews 11:6", "And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him."),
    DailyVerse("Isaiah 57:15", "For thus says the One who is high and lifted up, who inhabits eternity, whose name is Holy: I dwell in the high and holy place, and also with him who is of a contrite and lowly spirit, to revive the spirit of the lowly."),
    DailyVerse("John 14:13", "Whatever you ask in my name, this I will do, that the Father may be glorified in the Son."),
    DailyVerse("Colossians 1:13-14", "He has delivered us from the domain of darkness and transferred us to the kingdom of his beloved Son, in whom we have redemption, the forgiveness of sins."),
    DailyVerse("Romans 8:32", "He who did not spare his own Son but gave him up for us all, how will he not also with him graciously give us all things?"),
    DailyVerse("Matthew 5:16", "In the same way, let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven."),
    DailyVerse("John 15:7", "If you abide in me, and my words abide in you, ask whatever you wish, and it will be done for you."),
    DailyVerse("Ephesians 3:17-18", "So that Christ may dwell in your hearts through faith — that you, being rooted and grounded in love, may have strength to comprehend with all the saints what is the breadth and length and height and depth."),
    DailyVerse("Psalm 119:165", "Great peace have those who love your law; nothing can make them stumble."),
    DailyVerse("Isaiah 64:8", "But now, O Lord, you are our Father; we are the clay, and you are our potter; we are all the work of your hand."),
    DailyVerse("John 14:18", "I will not leave you as orphans; I will come to you."),
    DailyVerse("Romans 5:3-4", "Not only that, but we rejoice in our sufferings, knowing that suffering produces endurance, and endurance produces character, and character produces hope."),
    DailyVerse("Matthew 6:6", "But when you pray, go into your room and shut the door and pray to your Father who is in secret. And your Father who sees in secret will reward you."),
    DailyVerse("1 Peter 4:8", "Above all, keep loving one another earnestly, since love covers a multitude of sins."),
    DailyVerse("Philippians 4:19", "And my God will supply every need of yours according to his riches in glory in Christ Jesus."),
    DailyVerse("John 3:30", "He must increase, but I must decrease."),
    DailyVerse("Isaiah 40:11", "He will tend his flock like a shepherd; he will gather the lambs in his arms; he will carry them in his bosom, and gently lead those that are with young."),
    DailyVerse("Romans 6:14", "For sin will have no dominion over you, since you are not under law but under grace."),
    DailyVerse("Psalm 32:1", "Blessed is the one whose transgression is forgiven, whose sin is covered."),
    DailyVerse("Hebrews 13:5", "Keep your life free from love of money, and be content with what you have, for he has said, I will never leave you nor forsake you."),
    DailyVerse("John 15:11", "These things I have spoken to you, that my joy may be in you, and that your joy may be full."),
    DailyVerse("Matthew 11:30", "For my yoke is easy, and my burden is light."),
    DailyVerse("Romans 8:34", "Who is to condemn? Christ Jesus is the one who died — more than that, who was raised — who is at the right hand of God, who indeed is interceding for us."),
    DailyVerse("1 Corinthians 6:19-20", "Or do you not know that your body is a temple of the Holy Spirit within you, whom you have from God? You are not your own, for you were bought with a price. So glorify God in your body."),
    DailyVerse("Isaiah 41:13", "For I, the Lord your God, hold your right hand; it is I who say to you, Fear not, I am the one who helps you."),
    DailyVerse("John 8:31-32", "If you abide in my word, you are truly my disciples, and you will know the truth, and the truth will set you free."),
    DailyVerse("Colossians 4:2", "Continue steadfastly in prayer, being watchful in it with thanksgiving."),
    DailyVerse("Romans 12:21", "Do not be overcome by evil, but overcome evil with good."),
    DailyVerse("Matthew 5:7", "Blessed are the merciful, for they shall receive mercy."),
    DailyVerse("John 14:21", "Whoever has my commandments and keeps them, he it is who loves me. And he who loves me will be loved by my Father, and I will love him and manifest myself to him."),
    DailyVerse("Psalm 37:7", "Be still before the Lord and wait patiently for him."),
    DailyVerse("Isaiah 43:18-19", "Remember not the former things, nor consider the things of old. Behold, I am doing a new thing; now it springs forth, do you not perceive it?"),
    DailyVerse("1 John 2:17", "And the world is passing away along with its desires, but whoever does the will of God abides forever."),
    DailyVerse("Romans 8:39", "Nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord."),
    DailyVerse("John 14:26", "But the Helper, the Holy Spirit, whom the Father will send in my name, he will teach you all things and bring to your remembrance all that I have said to you."),
    DailyVerse("Psalm 103:1-2", "Bless the Lord, O my soul, and all that is within me, bless his holy name! Bless the Lord, O my soul, and forget not all his benefits."),
    DailyVerse("Hebrews 11:8", "By faith Abraham obeyed when he was called to go out to a place that he was to receive as an inheritance. And he went out, not knowing where he was going."),
    DailyVerse("Isaiah 49:15-16", "Can a woman forget her nursing child? Even these may forget, yet I will not forget you. Behold, I have engraved you on the palms of my hands."),
    DailyVerse("Romans 8:14", "For all who are led by the Spirit of God are sons of God."),
    DailyVerse("John 15:3", "Already you are clean because of the word that I have spoken to you."),
    DailyVerse("Philippians 2:13", "For it is God who works in you, both to will and to work for his good pleasure."),
    DailyVerse("Matthew 11:25", "At that time Jesus declared, I thank you, Father, Lord of heaven and earth, that you have hidden these things from the wise and understanding and revealed them to little children."),
    DailyVerse("Romans 11:33", "Oh, the depth of the riches and wisdom and knowledge of God! How unsearchable are his judgments and how inscrutable his ways!"),
    DailyVerse("Psalm 51:17", "The sacrifices of God are a broken spirit; a broken and contrite heart, O God, you will not despise."),
    DailyVerse("1 Corinthians 2:9", "But, as it is written, What no eye has seen, nor ear heard, nor the heart of man imagined, what God has prepared for those who love him."),
    DailyVerse("John 16:13", "When the Spirit of truth comes, he will guide you into all the truth."),
    DailyVerse("Isaiah 60:1", "Arise, shine, for your light has come, and the glory of the Lord has risen upon you."),
    DailyVerse("Romans 10:17", "So faith comes from hearing, and hearing through the word of Christ."),
    DailyVerse("Hebrews 10:35-36", "Therefore do not throw away your confidence, which has a great reward. For you have need of endurance, so that when you have done the will of God you may receive what is promised."),
    DailyVerse("John 16:24", "Until now you have asked nothing in my name. Ask, and you will receive, that your joy may be full."),
    DailyVerse("Colossians 3:16", "Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom, singing psalms and hymns and spiritual songs, with thankfulness in your hearts to God."),
    DailyVerse("Romans 8:16-17", "The Spirit himself bears witness with our spirit that we are children of God, and if children, then heirs — heirs of God and fellow heirs with Christ."),
    DailyVerse("John 17:3", "And this is eternal life, that they know you, the only true God, and Jesus Christ whom you have sent."),
    DailyVerse("Isaiah 30:18", "Therefore the Lord waits to be gracious to you, and therefore he exalts himself to show mercy to you. For the Lord is a God of justice; blessed are all those who wait for him."),
    DailyVerse("1 Thessalonians 5:23", "Now may the God of peace himself sanctify you completely, and may your whole spirit and soul and body be kept blameless at the coming of our Lord Jesus Christ."),
    DailyVerse("Matthew 5:5", "Blessed are the meek, for they shall inherit the earth."),
    DailyVerse("Romans 12:15", "Rejoice with those who rejoice, weep with those who weep."),
    DailyVerse("John 14:23", "Jesus answered him, If anyone loves me, he will keep my word, and my Father will love him, and we will come to him and make our home with him."),
    DailyVerse("Psalm 92:1-2", "It is good to give thanks to the Lord, to sing praises to your name, O Most High; to declare your steadfast love in the morning, and your faithfulness by night."),
    DailyVerse("Philippians 4:8", "Finally, brothers, whatever is true, whatever is honorable, whatever is just, whatever is pure, whatever is lovely, whatever is commendable, if there is any excellence, if there is anything worthy of praise, think about these things."),
    DailyVerse("Isaiah 53:4", "Surely he has borne our griefs and carried our sorrows."),
    DailyVerse("Hebrews 12:14", "Strive for peace with everyone, and for the holiness without which no one will see the Lord."),
    DailyVerse("John 15:12", "This is my commandment, that you love one another as I have loved you."),
    DailyVerse("Romans 5:5", "And hope does not put us to shame, because God's love has been poured into our hearts through the Holy Spirit who has been given to us."),
    DailyVerse("1 John 4:9", "In this the love of God was made manifest among us, that God sent his only Son into the world, so that we might live through him."),
    DailyVerse("John 14:15", "If you love me, you will keep my commandments."),
    DailyVerse("Isaiah 44:22", "I have blotted out your transgressions like a cloud and your sins like mist; return to me, for I have redeemed you."),
    DailyVerse("Colossians 2:6-7", "Therefore, as you received Christ Jesus the Lord, so walk in him, rooted and built up in him and established in the faith, just as you were taught, abounding in thanksgiving."),
    DailyVerse("Romans 8:5", "For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit set their minds on the things of the Spirit."),
    DailyVerse("John 6:68", "Simon Peter answered him, Lord, to whom shall we go? You have the words of eternal life."),
    DailyVerse("Matthew 6:13", "And lead us not into temptation, but deliver us from evil."),
    DailyVerse("Isaiah 7:14", "Therefore the Lord himself will give you a sign. Behold, the virgin shall conceive and give birth to a son, and shall call his name Immanuel."),
    DailyVerse("John 1:1", "In the beginning was the Word, and the Word was with God, and the Word was God."),
    DailyVerse("Luke 1:37", "For nothing will be impossible with God."),
    DailyVerse("Isaiah 9:6", "For to us a child is born, to us a son is given; and the government shall be upon his shoulder, and his name shall be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace."),
    DailyVerse("John 1:4-5", "In him was life, and the life was the light of men. The light shines in the darkness, and the darkness has not overcome it."),
    DailyVerse("Luke 2:10-11", "And the angel said to them, Fear not, for behold, I bring you good news of great joy that will be for all the people. For unto you is born this day in the city of David a Savior, who is Christ the Lord."),
    DailyVerse("Matthew 1:23", "Behold, the virgin shall conceive and bear a son, and they shall call his name Immanuel, which means God with us."),
    DailyVerse("Luke 2:14", "Glory to God in the highest, and on earth peace among those with whom he is pleased!"),
    DailyVerse("Isaiah 40:3", "A voice cries: In the wilderness prepare the way of the Lord; make straight in the desert a highway for our God."),
    DailyVerse("Luke 2:19", "But Mary treasured up all these things, pondering them in her heart."),
    DailyVerse("Isaiah 52:7", "How beautiful upon the mountains are the feet of him who brings good news, who publishes peace, who brings good news of happiness, who publishes salvation."),
    DailyVerse("John 1:16", "For from his fullness we have all received, grace upon grace."),
    DailyVerse("Luke 1:78-79", "Because of the tender mercy of our God, whereby the sunrise shall visit us from on high to give light to those who sit in darkness and in the shadow of death, to guide our feet into the way of peace."),
    DailyVerse("Revelation 22:20", "He who testifies to these things says, Surely I am coming soon. Amen. Come, Lord Jesus!"),
    DailyVerse("Isaiah 12:2", "Behold, God is my salvation; I will trust, and will not be afraid; for the Lord God is my strength and my song, and he has become my salvation."),
    DailyVerse("John 14:3", "And if I go and prepare a place for you, I will come again and will take you to myself, that where I am you may be also."),
    DailyVerse("Psalm 23:1-3", "The Lord is my shepherd; I shall not want. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul."),
    DailyVerse("Isaiah 9:2", "The people who walked in darkness have seen a great light; those who dwelt in a land of deep darkness, on them has light shone."),
    DailyVerse("Lamentations 3:22-23", "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.")
)

fun getDailyVerse(): DailyVerse {
    // 0-based day of year, matches Flutter: now.difference(DateTime(now.year, 1, 1)).inDays
    val dayOfYear = Calendar.getInstance().get(Calendar.DAY_OF_YEAR) - 1
    return verses[dayOfYear % verses.size]
}
